# Generated by Django 4.2 on 2023-04-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('fullDescription', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='цена')),
                ('count', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'products',
                'verbose_name_plural': 'products',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app_products.category'),
        ),
    ]
