# Generated by Django 4.2 on 2023-04-29 12:49

import app_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_remove_product_images_alter_cart_count_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=app_products.models.product_images_directory_path),
        ),
    ]
