# Generated by Django 4.2 on 2023-05-02 06:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0005_tags_specifications"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tags",
            old_name="tags",
            new_name="name",
        ),
    ]
